name: deploy-staging

on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          api_key: ${{ secrets.FORGE_API_KEY_STAGING }}
          server_id: ${{ secrets.FORGE_STAGING_SERVER_ID }}
          site_id: ${{ secrets.FORGE_STAGING_SITE_ID }}